server:
  port: 8888

spring:
  application:
    name: cropscan
  datasource: # MySQL数据库
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.224.164.169:3306/cropscan?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: mysql
    password: 123456
#  datasource: # PostgreSQL数据库
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: 123456
#    url: jdbc:postgresql://192.168.1.13:5432/postgres?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  jackson:
    default-property-inclusion: non-null
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
